# Generated by Django 5.0 on 2024-01-01 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
        ("topic", "0003_topic_topic_topic_title_f14aca_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["content"], name="questions_q_content_b1bebf_idx"
            ),
        ),
    ]
