# Generated by Django 5.0 on 2023-12-29 20:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=authentication.models.user_profile_image_filename,
            ),
        ),
    ]
