# Generated by Django 5.0 on 2024-01-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0005_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["id"], name="authenticat_id_9bf31e_idx"),
        ),
    ]
