# Generated by Django 5.0 on 2024-01-03 15:16

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_user_authenticat_id_9bf31e_idx"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authentication.models.CustomUserManager()),
            ],
        ),
    ]
