# Generated by Django 5.0 on 2023-12-29 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=5,
                        message="Title must be at least 3 characters long.",
                    ),
                    django.core.validators.RegexValidator(
                        code="invalid_title",
                        message="Title must be alphanumeric.",
                        regex="^[a-zA-Z0-9]*$",
                    ),
                ],
            ),
        ),
    ]
