# Generated by Django 5.0 on 2024-01-01 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0002_alter_topic_options_alter_topic_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["title"], name="topic_topic_title_f14aca_idx"),
        ),
    ]
