# Generated by Django 5.0 on 2024-01-03 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0003_topic_topic_topic_title_f14aca_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=5,
                        message="Title must be at least 3 characters long.",
                    )
                ],
            ),
        ),
    ]
